apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-to-text
spec:
  selector:
    matchLabels:
      app: audio-to-text
  template:
    metadata:
      labels:
        app: audio-to-text
    spec:
      containers:
      - name: audio-to-text
        image: navneetraju/video_benchmark:audio_analytics
        imagePullPolicy: Always
        env:
          - name: RMQ_ADDR
            value: rabbitmq.rabbits.svc.cluster.local
          - name: STREAM_ADDR
            value: 10.10.1.146
          - name: DB_API_ADDR
            value: db-api-service
          - name: DB_API_PORT
            value: '80'
        ports:
        - containerPort: 80
        volumeMounts:
          - name: host-test-mount
            mountPath: /tmp
      volumes:
        - name: host-test-mount
          hostPath:
              path: /mnt/test


