apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: stream-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-stream
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: response_latency_ms_99th
      targetAverageValue: 8
