apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: db-api-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: database-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: requests_per_second
      targetAverageValue: 8
